M48
; DRILL file {KiCad 9.0.7} date 2026-04-24T16:34:18-0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-24T16:34:18-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.100
%
G90
G05
T1
X97.25Y-49.305
X103.03Y-49.305
T2
X97.792Y-105.991
X100.332Y-105.991
M30
